version: '3'

services:
    web-app:
        build: WebApp
        ports:
            - "3200:3000"
   
    item-service:
        build: Item_Service
        ports:
            - "3452:8080"
    
    item-db:
        build: Item_DB
        ports:
            - "4567:3306"
         
    cart-service:
        build: Cart_Service
        ports:
            - "3252:8080"
            
    cart-db:
        image: redis
        ports:
            - "6379:6379"
    
    email-service:
        build: Email_Service
        ports:
            - "3253:8080"
    
    checkout-service:
        build: Checkout_Service
        ports:
            - "3254:8080"