version: '3'

services:
    web-app:
        build: react_app
        ports:
            - "3200:3000"
        stdin_open: true
        tty: true
   
    item-service:
        build: Item_Service
        ports:
            - "3452:8080"
    
    item-db:
        build: Item_DB
        ports:
            - "4567:3306"
         
    cart-service:
        build: Cart_Service
        ports:
            - "3252:8080"
            
    cart-db:
        image: redis
        ports:
            - "6379:6379"
    
    email-service:
        build: Email_Service
        ports:
            - "3253:8080"
    
    checkout-service:
        build: Checkout_Service
        ports:
            - "3254:8080"
            
    order-service:
        build: order-service
        
    order-db:
        build: order-db
        ports:
            - "4568:3306"
        
    api-gateway:
        build: api-gateway
        ports:
            - "7080:8080"
        
    user-db:
        build: user-db
        ports:
            - "4569:3306"
        
    svc-registry:
        build: Service_Registry
        ports:
            - "3255:8080"
            
    