version: '3'

services:
    web-app:
        build: WebApp
        ports:
            - "3200:3000"
   
    item-service:
        build: Item_Service
        ports:
            - "3452:8080"
    
    item-db:
        build: Item_DB
        ports:
            - "4567:3306"
         
    cart-service:
        build: Cart_Service
        ports:
            - "3252:8080"