FROM tomcat:8-jdk8-openjdk

ENV SERVER_PORT=8080
ENV registry.host=svc-registry
ENV ITEM_SERVICE_HOST=item-db
ENV ITEM_SERVICE_PORT=3306
ENV ITEM_SERVICE_USER=root
ENV ITEM_SERVICE_PASSWORD=password

Add /target/ROOT.war /usr/local/tomcat/webapps/