FROM tomcat:8-jdk8-openjdk

ENV ITEM_SERVICE_HOST=item_db
ENV ITEM_SERVICE_PORT=3306
ENV ITEM_SERVICE_USER=root
ENV ITEM_SERVICE_PASSWORD=password

Add /target/itemservice-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/