FROM tomcat:8-jdk8-openjdk

ENV SERVER_PORT=8080
ENV registry.host=svc-registry
ENV DB_HOSTNAME=order-db
ENV DB_HOST_PORT=3306
ENV DB_USER=root
ENV DB_PASSWORD=password

Add /target/ROOT.war /usr/local/tomcat/webapps/